# Generated by Django 5.1.4 on 2026-04-29 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], db_index=True, max_length=20)),
                ('part', models.CharField(blank=True, choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Part 3', 'Part 3')], help_text='Only meaningful for speaking prompts.', max_length=10)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='tenants.institute')),
            ],
            options={
                'ordering': ['skill', 'part', '-created_at'],
                'indexes': [models.Index(fields=['institute', 'skill', 'is_active'], name='content_pro_institu_7e28d1_idx')],
            },
        ),
    ]
