# Generated by Django 5.1.4 on 2026-04-29 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated events (cron, expiry).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(blank=True, help_text='Null for platform-level events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='tenants.institute')),
                ('target_user', models.ForeignKey(blank=True, help_text='The user this action affected, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['institute', '-created_at'], name='audit_audit_institu_59b212_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_55fb6e_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_5a2cbc_idx')],
            },
        ),
    ]
