# Generated by Django 5.1.4 on 2026-04-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_score',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
    ]
