# Generated by Django 5.1.4 on 2026-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_at_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_proficiency_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner (CEFR A1–A2)'), ('lower_intermediate', 'Lower Intermediate (CEFR B1)'), ('intermediate', 'Intermediate (CEFR B1–B2)'), ('upper_intermediate', 'Upper Intermediate (CEFR B2–C1)'), ('advanced', 'Advanced (CEFR C1–C2)')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('zh', 'Chinese (Mandarin)'), ('yue', 'Chinese (Cantonese)'), ('nl', 'Dutch'), ('fa', 'Farsi / Persian'), ('fil', 'Filipino / Tagalog'), ('fr', 'French'), ('de', 'German'), ('gu', 'Gujarati'), ('hi', 'Hindi'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja', 'Japanese'), ('kk', 'Kazakh'), ('ko', 'Korean'), ('ms', 'Malay'), ('ne', 'Nepali'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pa', 'Punjabi'), ('ru', 'Russian'), ('es', 'Spanish'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
