# Generated by Django 5.1.4 on 2026-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_english_proficiency_level_user_native_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_commitment_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_progress_slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_pref',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=8),
        ),
    ]
