# Generated by Django 5.1.4 on 2026-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_daily_commitment_minutes_user_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_subscores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
