# Generated by Django 5.1.4 on 2026-04-28 23:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('plan_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('max_users', models.PositiveIntegerField(default=50)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstituteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_target_score', models.FloatField(default=7.0)),
                ('allow_signup', models.BooleanField(default=True, help_text='Whether public signup is enabled')),
                ('custom_branding', models.JSONField(blank=True, default=dict)),
                ('feature_overrides', models.JSONField(blank=True, default=dict, help_text='Map of feature_flag -> bool, overriding plan_tier defaults')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.institute')),
            ],
        ),
    ]
