# Generated by Django 5.1.4 on 2026-04-28 23:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_listening_session',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_li_user_id_7cdf25_idx'), models.Index(fields=['institute', '-created_at'], name='practice_li_institu_8cbc8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('passage_title', models.CharField(blank=True, max_length=300)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_reading_session',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_re_user_id_db89b7_idx'), models.Index(fields=['institute', '-created_at'], name='practice_re_institu_83b54d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=500)),
                ('mode', models.CharField(choices=[('Standard', 'Standard'), ('RolePlay', 'Role Play')], default='Standard', max_length=20)),
                ('prompt', models.JSONField(blank=True, help_text='{ part, text } if structured', null=True)),
                ('transcript', models.JSONField(default=list, help_text='Array of Turn objects')),
                ('analysis', models.JSONField(blank=True, help_text='SpeakingAnalysis (set after analysis)', null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_speaking_session',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_sp_user_id_a01a30_idx'), models.Index(fields=['institute', '-created_at'], name='practice_sp_institu_0f8c56_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.JSONField(help_text='StudyPlan object — array of DailyGoal')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_study_plan',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_st_user_id_16b830_idx'), models.Index(fields=['institute', '-created_at'], name='practice_st_institu_83f185_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeaknessAnalysisCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], db_index=True, max_length=20)),
                ('analysis', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_weakness_cache',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_we_user_id_28a9ff_idx'), models.Index(fields=['institute', '-created_at'], name='practice_we_institu_71ea72_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'skill'), name='unique_active_weakness_analysis_per_user_skill')],
            },
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('essay', models.TextField()),
                ('band_score', models.FloatField()),
                ('feedback', models.JSONField(help_text='Full WritingFeedback object')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_writing_session',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_wr_user_id_9b59e0_idx'), models.Index(fields=['institute', '-created_at'], name='practice_wr_institu_a49e3f_idx')],
            },
        ),
    ]
