# Generated by Django 5.1.4 on 2026-04-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='transcript',
            field=models.TextField(blank=True, help_text='Audio script text — kept for replay/review.'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='passage_content',
            field=models.TextField(blank=True, help_text='Original passage text — kept for replay/review.'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='writingsession',
            name='band_score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
