# Generated by Django 5.1.4 on 2026-04-29 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_listeningsession_transcript_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Grammar', 'Grammar'), ('Vocabulary', 'Vocabulary')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text="Array of option strings, e.g. ['A...', 'B...', 'C...', 'D...']")),
                ('correct_answer', models.CharField(help_text="The correct option letter, e.g. 'A'.", max_length=10)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(blank=True, help_text='Null = global question (shared across all institutes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
            ],
            options={
                'db_table': 'practice_quiz_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'difficulty'], name='practice_qu_categor_f4ceaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Grammar', 'Grammar'), ('Vocabulary', 'Vocabulary')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('questions_snapshot', models.JSONField(blank=True, default=list, help_text='Frozen copy of the questions/answers shown to the user.')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_quiz_session',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_qu_user_id_38173e_idx'), models.Index(fields=['institute', '-created_at'], name='practice_qu_institu_9b39a1_idx')],
            },
        ),
    ]
