# Generated by Django 5.1.4 on 2026-04-29 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_listeningsession_deleted_at_quizsession_deleted_at_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='band_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts', to='practice.listeningsession'),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='predicted_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='band_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts', to='practice.readingsession'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='predicted_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='fluency_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts', to='practice.speakingsession'),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='part',
            field=models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3'), ('mixed', 'Mixed')], db_index=True, default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='predicted_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts', to='practice.writingsession'),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='predicted_band',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writingsession',
            name='task_type',
            field=models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], db_index=True, default='task2', max_length=10),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('dashboard', 'Dashboard snapshot'), ('session', 'Single session')], default='dashboard', max_length=20)),
                ('target_id', models.UUIDField(blank=True, help_text='Session id when scope=session.', null=True)),
                ('period_days', models.PositiveIntegerField(default=30)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_share_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('session_id', models.UUIDField()),
                ('predicted_band', models.DecimalField(decimal_places=1, max_digits=3)),
                ('actual_band', models.DecimalField(decimal_places=1, max_digits=3)),
                ('delta', models.DecimalField(decimal_places=1, help_text='predicted - actual', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_calibration_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_ca_user_id_f343b4_idx'), models.Index(fields=['user', 'session_type'], name='practice_ca_user_id_b92c7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('regression', 'Regression'), ('streak_lost', 'Streak Lost'), ('inactive', 'Inactive'), ('goal_reached', 'Goal Reached'), ('quick_win', 'Quick Win Suggestion')], max_length=24)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Numbers/links to render the alert.')),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_target', models.CharField(blank=True, help_text='Section name / route id', max_length=80)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_dashboard_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'dismissed_at'], name='practice_da_user_id_bd5fc7_idx'), models.Index(fields=['user', '-created_at'], name='practice_da_user_id_eb26b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErrorCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_session_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('source_session_id', models.UUIDField()),
                ('category', models.CharField(choices=[('grammar', 'Grammar'), ('lexical', 'Lexical'), ('pronunciation', 'Pronunciation'), ('coherence', 'Coherence'), ('task_response', 'Task Response'), ('fluency', 'Fluency'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('error_text', models.TextField(help_text='The original problem (sentence, phrase, or pattern).')),
                ('correction_text', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease', models.FloatField(default=2.5)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, help_text='Mastered or dismissed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_error_card',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['user', 'due_at'], name='practice_er_user_id_31ec09_idx'), models.Index(fields=['user', 'archived_at'], name='practice_er_user_id_4803b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('overall_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('readiness_score', models.FloatField(blank=True, help_text='0-100; higher = closer to test-day ready', null=True)),
                ('sub_results', models.JSONField(default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('listening_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.listeningsession')),
                ('reading_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.readingsession')),
                ('speaking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.speakingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to=settings.AUTH_USER_MODEL)),
                ('writing_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.writingsession')),
            ],
            options={
                'db_table': 'practice_mock_test',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='practice_mo_user_id_48ebeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lemma', models.CharField(db_index=True, max_length=100)),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='', max_length=2)),
                ('is_awl', models.BooleanField(default=False, help_text='On the Academic Word List')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('last_session_type', models.CharField(blank=True, choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('listening', 'Listening')], default='', max_length=10)),
                ('last_session_id', models.UUIDField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_vocabulary_observation',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'cefr_level'], name='practice_vo_user_id_fb2397_idx'), models.Index(fields=['user', '-last_seen_at'], name='practice_vo_user_id_c6124e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lemma'), name='unique_vocab_per_user_lemma')],
            },
        ),
    ]
