# Generated by Django 5.1.4 on 2026-04-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_listeningsession_band_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabularyobservation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
