# Generated by Django 5.1.4 on 2026-04-29 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_mocktest_deleted_at_vocabularyobservation_deleted_at'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingsession',
            name='accent',
            field=models.CharField(choices=[('uk', 'UK'), ('us', 'US'), ('au', 'Australia'), ('nz', 'New Zealand'), ('ca', 'Canada')], default='uk', max_length=4),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='cue_card',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='examiner_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='mock_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='persona',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('strict', 'Strict'), ('friendly', 'Friendly'), ('formal', 'Formal')], default='neutral', max_length=12),
        ),
        migrations.AlterField(
            model_name='speakingsession',
            name='mode',
            field=models.CharField(choices=[('Standard', 'Standard'), ('RolePlay', 'Role Play'), ('Mock', 'Mock Test')], default='Standard', max_length=20),
        ),
        migrations.CreateModel(
            name='CueCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=300)),
                ('bullets', models.JSONField(help_text='Array of 3-5 bullet prompt lines.')),
                ('category', models.CharField(choices=[('personal', 'Personal Experience'), ('place', 'Places'), ('object', 'Objects & Things'), ('event', 'Events'), ('person', 'People'), ('media', 'Media & Entertainment'), ('technology', 'Technology'), ('environment', 'Environment'), ('education', 'Education'), ('work', 'Work & Career'), ('custom', 'Custom')], db_index=True, default='personal', max_length=24)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8)),
                ('follow_up_questions', models.JSONField(blank=True, default=list, help_text='Suggested Part 3 follow-ups linked to this Part 2 topic.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(blank=True, help_text='Null = global card visible to all institutes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
            ],
            options={
                'db_table': 'practice_cue_card',
                'ordering': ['topic'],
                'indexes': [models.Index(fields=['category', 'difficulty', 'is_active'], name='practice_cu_categor_6e8512_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('session_id', models.UUIDField(db_index=True)),
                ('body', models.TextField()),
                ('transcript_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_annotations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_session_annotation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_type', 'session_id'], name='practice_se_session_72aec2_idx'), models.Index(fields=['student', '-created_at'], name='practice_se_student_b068c6_idx')],
            },
        ),
    ]
