# Generated by Django 5.1.4 on 2026-04-29 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_speakingsession_accent_speakingsession_cue_card_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('srs_due', 'SRS due'), ('streak_risk', 'Streak risk'), ('instructor_note', 'Instructor note'), ('weekly_digest', 'Weekly digest'), ('goal_reached', 'Goal reached'), ('exam_reminder', 'Exam reminder'), ('system', 'System')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_target', models.CharField(blank=True, help_text='Section name or route id', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='practice_no_user_id_db11bc_idx'), models.Index(fields=['user', 'dismissed_at'], name='practice_no_user_id_a2fc78_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('browser_push', 'Browser push'), ('email', 'Email')], max_length=16)),
                ('events', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_notification_pref',
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_pref_per_user_channel')],
            },
        ),
        migrations.CreateModel(
            name='WritingDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt', models.TextField()),
                ('essay', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('task_type', models.CharField(default='task2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_writing_draft',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='practice_wr_user_id_672104_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'prompt_hash'), name='unique_draft_per_user_prompt')],
            },
        ),
    ]
