# Generated by Django 5.1.4 on 2026-04-30 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_notification_notificationpreference_writingdraft'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_badge',
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['user', '-awarded_at'], name='practice_ba_user_id_7d994e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_badge_per_user')],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_date', models.DateField(db_index=True)),
                ('skill', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('listening', 'Listening')], max_length=10)),
                ('prompt', models.TextField(help_text='Short challenge text shown on Today.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_daily_challenge',
                'ordering': ['-challenge_date'],
                'indexes': [models.Index(fields=['user', '-challenge_date'], name='practice_da_user_id_0f6bf5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge_date'), name='unique_daily_challenge_per_user_per_day')],
            },
        ),
    ]
