# Generated by Django 5.1.4 on 2026-04-30 03:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_badge_dailychallenge'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebateRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('completed', 'Completed'), ('aborted', 'Aborted')], db_index=True, default='waiting', max_length=12)),
                ('target_band', models.DecimalField(decimal_places=1, default=7.0, help_text='Average target band of participants — used by matching.', max_digits=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('moderator_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
            ],
            options={
                'db_table': 'practice_debate_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('solo_baseline_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_seats', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='practice.debateroom')),
            ],
            options={
                'db_table': 'practice_debate_participant',
            },
        ),
        migrations.CreateModel(
            name='MockTestBankItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing')], db_index=True, max_length=10)),
                ('topic', models.CharField(db_index=True, max_length=40)),
                ('target_band', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('payload', models.JSONField(help_text='Full test payload — same shape the FE expects from the live agent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'practice_mock_test_bank_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill', 'topic'], name='practice_mo_skill_94432b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], max_length=10)),
                ('session_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('sla_due_at', models.DateTimeField()),
                ('student_notes', models.TextField(blank=True, help_text='Optional: what the student wants the marker to focus on.')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('marker_band_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('marker_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_review_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('hourly_rate_cents', models.PositiveIntegerField(default=0, help_text='Listed rate; payment is stubbed.')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('languages', models.JSONField(blank=True, default=list, help_text='ISO codes the tutor teaches in.')),
                ('specialities', models.JSONField(blank=True, default=list, help_text="e.g. ['speaking-part-2','task-2-essays']")),
                ('availability', models.JSONField(blank=True, default=dict, help_text='Day-of-week → list of [start,end] hour pairs.')),
                ('rating_avg', models.FloatField(blank=True, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profiles', to='tenants.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_tutor_profile',
                'ordering': ['-rating_avg', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=12)),
                ('rate_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('marker_payout_id', models.CharField(blank=True, default='', max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('student_notes', models.TextField(blank=True)),
                ('tutor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('speaking_session', models.ForeignKey(blank=True, help_text='Filled when the booking goes LIVE and a speaking session row is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.speakingsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_bookings_made', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='practice.tutorprofile')),
            ],
            options={
                'db_table': 'practice_tutor_booking',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.AddIndex(
            model_name='debateroom',
            index=models.Index(fields=['institute', 'status'], name='practice_de_institu_fd9920_idx'),
        ),
        migrations.AddConstraint(
            model_name='debateparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_debate_seat'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['institute', 'status', 'sla_due_at'], name='practice_re_institu_794004_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['user', '-created_at'], name='practice_re_user_id_04d8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorbooking',
            index=models.Index(fields=['tutor', 'scheduled_for'], name='practice_tu_tutor_i_e27cea_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorbooking',
            index=models.Index(fields=['student', '-scheduled_for'], name='practice_tu_student_0245f7_idx'),
        ),
    ]
