# Generated by Django 5.1.4 on 2026-04-30 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_debateroom_debateparticipant_mocktestbankitem_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOptIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cross_institute_ok', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_opt_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_partner_opt_in',
            },
        ),
        migrations.CreateModel(
            name='PartnerSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(help_text='0..1; higher = more lexically similar.')),
                ('target_band_delta', models.FloatField(help_text='Absolute difference in target_score.')),
                ('suggested_task', models.TextField(blank=True, help_text='One concrete shared task for the week.')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_partner_suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetBandHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_target', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('new_target', models.DecimalField(decimal_places=1, max_digits=3)),
                ('source', models.CharField(choices=[('onboarding', 'Onboarding'), ('manual', 'Manual'), ('auto_tuner', 'Auto-tuner')], max_length=16)),
                ('accepted', models.BooleanField(default=True, help_text='False if the auto-tuner suggested but the user declined.')),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_band_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_target_band_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(db_index=True, max_length=64)),
                ('criterion', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_id', models.UUIDField(blank=True, help_text='Session id / row id the feedback came from. Optional.', null=True)),
                ('helpful', models.BooleanField(db_index=True)),
                ('reason', models.CharField(blank=True, choices=[('', ''), ('wrong_band', 'Wrong band'), ('missed_errors', 'Missed errors'), ('too_generic', 'Too generic'), ('other', 'Other')], default='', max_length=32)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_feedback_vote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='practice_fe_agent_e91dfb_idx'), models.Index(fields=['institute', '-created_at'], name='practice_fe_institu_db13ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.CharField(blank=True, default='', help_text='Daily rotating prompt or empty for free talk.', max_length=300)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('transcript', models.TextField(blank=True)),
                ('fluency_metrics', models.JSONField(blank=True, null=True)),
                ('lexical_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_voice_journal_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='practice_vo_user_id_182101_idx')],
            },
        ),
    ]
