# Generated by Django 5.1.4 on 2026-04-30 15:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_partneroptin_partnersuggestion_targetbandhistory_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingsession',
            name='live_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingsession',
            name='whisper_hints_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speakingsession',
            name='mode',
            field=models.CharField(choices=[('Standard', 'Standard'), ('RolePlay', 'Role Play'), ('Mock', 'Mock Test'), ('Warmup', 'Warm-up')], default='Standard', max_length=20),
        ),
        migrations.CreateModel(
            name='CueCardConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cue_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='practice.cuecard')),
                ('speaking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='practice.speakingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cue_card_uses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_cue_card_consumption',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user', '-used_at'], name='practice_cu_user_id_40c47a_idx'), models.Index(fields=['user', 'cue_card'], name='practice_cu_user_id_2dabd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_index', models.IntegerField(help_text='Index into session.transcript at the time of bookmark.')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.institute')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='practice.speakingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_session_bookmark',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='practice_se_session_83172a_idx'), models.Index(fields=['user', '-created_at'], name='practice_se_user_id_0df111_idx')],
            },
        ),
    ]
